# Generated by Django 5.0.1 on 2024-02-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
